# Generated by Django 2.1.4 on 2019-01-03 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0002_task_completed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='Complete_date',
        ),
        migrations.RemoveField(
            model_name='task',
            name='Task_Discription',
        ),
        migrations.RemoveField(
            model_name='task',
            name='Task_Name',
        ),
        migrations.RemoveField(
            model_name='task',
            name='completed',
        ),
        migrations.AddField(
            model_name='task',
            name='accomplish_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='finish_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='start_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='task_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='task_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
